name: Feature request
description: Suggest an improvement to Sponskip.
title: "feature: "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What would this improve for YouTube viewers?
    validations:
      required: true
  - type: textarea
    id: outcome
    attributes:
      label: Proposed outcome
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
